import Head from "next/head";
import { useEffect } from "react";
import { AuthProvider } from "../context/auth-context";
import { LoadingProvider } from "../context/loading-context";
import { ToastProvider } from "../context/toast-context";
/*all css import*/
import "../../styles/main.css";
import AuthGuard from "../guard/auth.guard";
import { Provider } from "react-redux";
import { store } from "../store";

const Guard = ({ children, authGuard }) => {
  if (!authGuard) {
    return <>{children}</>;
  } else {
    return <AuthGuard>{children}</AuthGuard>;
  }
};

function MyApp({ Component, pageProps }) {
  const authGuard = Component.authGuard ?? false;

  useEffect(() => {
    import("../../public/assets/js/bootstrap.bundle.min.js");
  });
  return (
    <Provider store={store}>
      <ToastProvider>
        <LoadingProvider>
          <AuthProvider>
            <Guard authGuard={authGuard}>
              <Head>
                <title>Scooby - Petcare & Pet Shop NextJs Template</title>
                <meta
                  name="description"
                  content="Generated by create next app"
                />
                <link rel="icon" href="assets/images/sm-logo.svg" />
              </Head>
              <Component {...pageProps} />
            </Guard>
          </AuthProvider>
        </LoadingProvider>
      </ToastProvider>
    </Provider>
  );
}

export default MyApp;
